###
GET localhost:8081/menu
Content-Type: application/json

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"3755f358-2989-4bc9-87ac-cd45a02589d0"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"35cf443a-f87f-494e-ab38-487d012c1752"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"fbc31ee3-67d8-4d96-8fcd-d3119dbed3b2"

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "3755f358-2989-4bc9-87ac-cd45a02589d0",
  "amount": 2
}

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "35cf443a-f87f-494e-ab38-487d012c1752",
  "amount": 0
}

###
POST localhost:8081/cart/1/pay
