###
GET localhost:8081/menu
Content-Type: application/json

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"8b15ba86-832a-4038-a963-f1f0670f309c"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"3fac67f4-d41c-4fef-bda7-d1a1ddc9befd"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"57702cb5-6844-4224-8694-b0367405e18b"

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "57702cb5-6844-4224-8694-b0367405e18b",
  "amount": 2
}

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "3fac67f4-d41c-4fef-bda7-d1a1ddc9befd",
  "amount": 0
}

###
POST localhost:8081/cart/1/pay
