###
GET localhost:8081/menu
Content-Type: application/json

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"8ed199c4-5ae9-429c-8b68-193521d349f6"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"293abaa4-3a13-48fb-914f-f77168723d38"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"c1601a58-6194-42e5-92a8-5f7b31464fee"

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "8ed199c4-5ae9-429c-8b68-193521d349f6",
  "amount": 2
}

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "293abaa4-3a13-48fb-914f-f77168723d38",
  "amount": 0
}

###
POST localhost:8081/cart/1/pay
