###
GET localhost:8081/menu
Content-Type: application/json

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"5c3fff5b-d2b1-4417-99e9-8bed804bf669"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"f4217f1e-3feb-4320-b405-29783cc39697"

###
POST localhost:8081/cart/1/add
Content-Type: application/json

"e88f60ae-1435-466d-8278-5ff8899dd90e"

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "e88f60ae-1435-466d-8278-5ff8899dd90e",
  "amount": 3
}

###
PUT localhost:8081/cart/1/change
Content-Type: application/json

{
  "menuItemId": "f4217f1e-3feb-4320-b405-29783cc39697",
  "amount": 0
}

###
POST localhost:8081/cart/1/pay
