###
GET localhost:9200/item

###
GET localhost:9200/item/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "description": "сладкий зеленый голубой"
          }
        },
        {
          "match": {
            "name": "сладкий зеленый голубой"
          }
        }
      ]
    }
  }
}