
###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Цыплёнок Грин",
  "description": "Сочное куриное филе,сыр моцарелла, сладкий зелёный перец, соус «Чесночный рэнч», чеснок и томаты.",
  "price": 549.0,
  "category": "Пицца",
  "routeCard": [
    {
      "name": "Порезать лук",
      "products": [
        {
          "name": "Лук",
          "amount": 1.0
        }
      ]
    }
  ]
}

###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Микс Грин",
  "description": "Соус «Тысяча островов», шампиньоны, лук, сладкий зелёный перец и пикантная пепперони",
  "price": 549.0,
  "category": "Пицца",
  "routeCard": [
    {
      "name": "Порезать лук",
      "products": [
        {
          "name": "Лук",
          "amount": 1.0
        }
      ]
    }
  ]
}

###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Чеддер Чизбургер",
  "description": "Яркий сыр Чеддер, Моцарелла, хрустящий бекон, говядина, маринованные огурчики, томаты, соус 1000 островов. И много всякого интересного",
  "price": 599.0,
  "category": "Пицца",
  "routeCard": [
    {
      "name": "Порезать лук",
      "products": [
        {
          "name": "Лук",
          "amount": 1.0
        }
      ]
    }
  ]
}

###
POST http://localhost:8080/item
Content-Type: application/json;charset=utf-8

{
  "name": "С грушей и голубым сыром",
  "description": "Нежная пицца со сладкой грушей, ароматным блю чиз, сливочным сыром и хрустящим миндалем.",
  "price": 599.0,
  "category": "Пицца",
  "routeCard": [
    {
      "name": "Порезать лук",
      "products": [
        {
          "name": "Лук",
          "amount": 1.0
        }
      ]
    }
  ]
}