###
GET http://localhost:8080/items
Content-Type: application/json

###
GET http://localhost:8080/item/sdfsadf
Content-Type: application/json

###
GET http://localhost:8080/find/сладкий зелёный голубой
Content-Type: application/json

###
POST http://localhost:8080/publish
Content-Type: application/json

["45d56ef2-966b-44b2-bd57-9fe6f2dfa471",
  "5db22793-6119-4dcf-9657-fc8a8423930f",
  "e6164f52-91a1-4acf-8a66-674706bdb5e6"]
