###
GET http://localhost:8080/items
Content-Type: application/json

###
GET http://localhost:8080/item/sdfsadf
Content-Type: application/json

###
GET http://localhost:8080/find/сладкий зелёный голубой
Content-Type: application/json

###
POST http://localhost:8080/publish
Content-Type: application/json

["57702cb5-6844-4224-8694-b0367405e18b", "3fac67f4-d41c-4fef-bda7-d1a1ddc9befd", "8b15ba86-832a-4038-a963-f1f0670f309c"]