###
GET http://localhost:8080/menus
Content-Type: application/json

###
POST http://localhost:8080/menus
Content-Type: application/json

{
  "name": "daily",
  "items": {
    "items": [
      {"name": "eggs", "price": 100},
      {"name": "steak", "price": 1000}
    ]
  }
}

###
GET http://localhost:8080/menu/daily
Content-Type: application/json