###
GET http://localhost:8080/orders
Content-Type: application/json

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": 1,
  "user": {
    "id": 1,
    "name": "John",
    "age": 20,
    "countryOfResidence": "RF"
  },
  "status": "Оплачен",
  "orderItems": [
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 1,
        "name": "eggs",
        "price": 100.0
      },
      "menuPrice": 100.0,
      "quantity": 2
    },
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 2,
        "name": "steak",
        "price": 1000.0
      },
      "menuPrice": 1000.0,
      "quantity": 1
    }
  ]
}

###
GET http://localhost:8080/order/1
Content-Type: application/json

###
PUT http://localhost:8080/order/1
Content-Type: application/json

{
  "id": 1,
  "user": {
    "id": 1,
    "name": "John",
    "age": 20,
    "countryOfResidence": "RF"
  },
  "status": "Оплачен",
  "orderItems": [
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 1,
        "name": "eggs",
        "price": 100.0
      },
      "menuPrice": 100.0,
      "quantity": 2
    },
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 2,
        "name": "steak",
        "price": 1000.0
      },
      "menuPrice": 1000.0,
      "quantity": 1
    },
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 3,
        "name": "tea",
        "price": 50.0
      },
      "menuPrice": 50.0,
      "quantity": 1
    }
  ]
}

###
PUT http://localhost:8080/order/1?status=Выполнен
Content-Type: application/json

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": 2,
  "user": {
    "id": 2,
    "name": "Маша",
    "age": 21,
    "countryOfResidence": "RF"
  },
  "status": "Оплачен",
  "orderItems": [
    {
      "menu": {
        "id": 1,
        "name": "daily"
      },
      "item": {
        "id": 3,
        "name": "tea",
        "price": 50.0
      },
      "menuPrice": 50.0,
      "quantity": 2
    }
  ]
}

###
GET http://localhost:8080/orders/Выполнен
Content-Type: application/json

###
DELETE http://localhost:8080/order/1
Content-Type: application/json

###
GET http://localhost:8080/orders
Content-Type: application/json