version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  zookeeper-pizza:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-pizza:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.64
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-pizza:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  menu:
    image: reactive-pizza-menu
    container_name: reactive-pizza-menu
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: menu
    environment:
      KAFKA:
      ELASTIC:
    ports:
      - 8080:8080

  payment:
    image: reactive-pizza-payment
    container_name: reactive-pizza-payment
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: payment
    environment:
      KAFKA:
      ELASTIC:
    ports:
      - 8082:8082

  cart:
    image: reactive-pizza-cart
    container_name: reactive-pizza-cart
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: cart
    environment:
      KAFKA:
      ELASTIC:
      PAYMENT_SERVER:
    ports:
      - 8081:8081

  order:
    image: reactive-pizza-order
    container_name: reactive-pizza-order
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: order
    environment:
      KAFKA:
      ELASTIC:
    ports:
      - 8083:8083

  kitchen:
    image: reactive-pizza-kitchen
    container_name: reactive-pizza-kitchen
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: kitchen
    environment:
      KAFKA:
      ELASTIC:
    ports:
      - 8084:8084

  waiter-bot:
    image: reactive-pizza-waiter-bot
    container_name: reactive-pizza-waiter-bot
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        SERVICE: waiter-bot
    environment:
      KAFKA:
      ELASTIC:
      ORDER_SERVER:
